#!/bin/bash
DIR=$(echo "${0%/*}")
SROOTBASE=$(cd "$DIR" && echo "$(pwd -L)")
METAPROJECT=$1
shift

eval `$SROOTBASE/setup.sh`

if [ -e "$METAPROJECT/env-shell.sh" ]; then
    $METAPROJECT/env-shell.sh $@
else
    $SROOT/metaprojects/$METAPROJECT/env-shell.sh $@
fi
