#!/bin/bash
DIR=$(echo "${0%/*}")
SROOTBASE=$(cd "$DIR" && echo "$(pwd -L)")
METAPROJECT=$1
shift

eval `$SROOTBASE/setup.sh`

if [ -x "$METAPROJECT/bin/icetray-shell" ]; then
    $METAPROJECT/bin/icetray-shell $@
elif [ -x "$METAPROJECT/env-shell.sh" ]; then
    $METAPROJECT/env-shell.sh $@
elif [ -x "$SROOT/metaprojects/$METAPROJECT/bin/icetray-shell" ]; then
    $SROOT/metaprojects/$METAPROJECT/bin/icetray-shell $@
else
    $SROOT/metaprojects/$METAPROJECT/env-shell.sh $@
fi
